apiVersion: v1
kind: ReplicationController
metadata:
  name: firstrc
  labels:
    name: firstrc
spec:
  replicas: 2
  selector:
    app: myapp
    type: frontend
  template:
    metadata:
      name: pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: container
          image: coolgourav147/nginx-custom
  