apiVersion: v1
kind: Service
metadata:
  name: myfirstservice
  labels:
    servicelbl: labelname
spec:
  type: NodePort
  selector:
    type: app  # this is important, service will do loadbalancing across all the pods matching this label.    
  ports:
  - nodePort: 32000     # This is the port on which the service will be exposed on every node in the cluster. 
    port: 9000          # This is the port number on which the service will listen within the Kubernetes cluster. 
    targetPort: 80      # This is the port number to which the incoming traffic will be forwarded within the pods managed by the service


# With this setup, external traffic coming to the node's IP on port 32000 will be forwarded to the pods' port 80, 
# and within the cluster, other services or pods can communicate with this service on port 9000.
