apiVersion: v1
kind: Pod

metadata:
  name: myfirstpod
  labels: 
    env: tests

spec:
  containers:
    - name: firstc
      image: coolgourav147/nginx-custom
      env:
        - name: myname
          value: Sam
        - name: lastName
          value: Chahal
