apiVersion: v1
kind: Pod

metadata:
  name: myfirstpod
  labels: 
    env: tests

spec:
  containers:
    - name: firstc
      image: coolgourav147/nginx-custom
      env:
        - name: myname
          value: Sam
        - name: lastName
          value: Chahal
      args: ["sleep", "3600"]
    - name: secondc
      image: coolgourav147/nginx-custom
      env:
        - name: myname
          value: Sam
        - name: lastName
          value: Chahal
  initContainers:
    - name: firstInitContainer
      image: coolgourav147/nginx-custom
      env:
        - name: myname
          value: Sam
        - name: lastName
          value: Chahal
      args: ["sleep", "10"]
